---
build_from:
  aarch64: ghcr.io/hassio-addons/base-nodejs:0.2.5
  amd64: ghcr.io/hassio-addons/base-nodejs:0.2.5
  armhf: ghcr.io/hassio-addons/base-nodejs:0.2.5
  armv7: ghcr.io/hassio-addons/base-nodejs:0.2.5
  i386: ghcr.io/hassio-addons/base-nodejs:0.2.5

# Signing configuration
codenotary:
  signer: lorenzo.lingua@gmail.com
  base_image: ghcr.io/hassio-addons/base-nodejs:0.2.5

# No custom args needed; Supervisor injects BUILD_FROM based on build_from mapping.
