---
name: PantryOS
version: "dev-12"
description: Gestione della dispensa con interfaccia React
url: https://github.com/llingua/pantryos
slug: pantryos
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
hassio_api: true
homeassistant_api: true
host_network: false
ingress: true
ingress_port: 3000
ingress_entry: /
panel_icon: mdi:food
panel_title: PantryOS
panel_admin: true
ports: {}
map:
  - config:rw
  - ssl:ro
  - share:rw
  - media:rw
  - backup:rw

# Configurazione predefinita
options:
  log_level: info
  timezone: Europe/Rome
  culture: it
  currency: EUR
  auth_proxy: true
  auth_proxy_header: X-WebAuth-User
  trusted_proxies: []
  host: 0.0.0.0
  port: 3000
  base_path: /
  database_path: /data/pantryos
  backup_enabled: true
  backup_retention_days: 30
  notifications_enabled: true
  email_notifications: false
  push_notifications: true

# Schema di validazione per le opzioni
schema:
  log_level: str
  timezone: str
  culture: str
  currency: str
  auth_proxy: bool
  auth_proxy_header: str
  trusted_proxies: [str]
  host: str
  port: int(1,65535)
  base_path: str
  database_path: str
  backup_enabled: bool
  backup_retention_days: int(1,365)
  notifications_enabled: bool
  email_notifications: bool
  push_notifications: bool
