---
name: PantryOS
version: dev-9.1
slug: pantryos
description: Gestione della dispensa con interfaccia React e backend Node.js
url: https://github.com/llingua/pantryOS
stage: experimental
arch:
  - aarch64
  - armv7
  - amd64
init: false
startup: services
ingress: true
ingress_port: 8099
panel_icon: mdi:food-apple
map:
  - data:rw
options: {}
schema: {}
